### ISSUE TITLE
The Error "Host name may not be empty"

### ISSUE THREAD

**Issue by JattJames** [coldbox-modules/hyper#13]
Trying to use the API for this but it is coming as an error 

<cfset Application.hyper = new models.HyperRequest()>
<cfscript>
	Application.hyper.setMethod("POST")
    	.setUrl('https://demo2.2c2p.com/2C2PFrontEnd/RedirectV3/payment')
    	.setBody({
        	version: '8.5',
        	merchant_id: 'JT04',
        	currency: '702',
        	result_url_1: 'http://localhost:8888/hyper/result.cfm',
        	hash_value: hash_value,
        	payment_description: 'Test',
        	order_id : '#Timeformat(now())#',
        	amount : '000000002500'
    	}).send();
</cfscript>	

"Host name may not be empty"

**Comment by elpete** [comment]
Fixed in v2.2.1.
