### ISSUE TITLE
The response is not json.

### ISSUE THREAD

**Issue by randy-johnson** [coldbox-modules/hyper#39]
Hello,

Thank you for this fantastic module.  I found it a couple of days ago while researching.

The response below is an error message from the Authorize.net API.  The API is XML, but they offer JSON support through a translation of JSON elements to XML elements.

I ran into an issue today while testing and want to get your advice.

First, I understand why I am getting the actual error message in the API response.  I can fix that.  The focus is the special character at the start of the JSON string causing the issue.

I was able to see that there was a special character until I put the code into tryCF

https://trycf.com/gist/3ae99238fce08639be09390b7bfc344b/lucee5?theme=monokai

```
﻿{"messages":{"resultCode":"Error","message":[{"code":"E00003","text":"The element 'transactionRequest' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd' has invalid child element 'userFields' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'. List of possible elements expected: 'transactionType' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'."}]}}
```
Once I spotted the special character, I was able to get around it by doing the following:

```
ret.data = res.getData();      
        ret.json = "";

        if (isJSON(ret.data)){
            ret.json = res.json();
        } else {
            if (left(ret.data,1)!='{') {
                ret.dataClean= removeChars(ret.data,1,1); 
                if (isJSON(ret.dataClean)) {
                    ret.json = deserializeJSON(ret.dataClean);
                }
            }
        }

        ret.isSuccess = res.isSuccess();
```

That seemed to work for me.  Is there a better way to handle it using the current module functions?  

Is something like this worthy of consideration for inclusion in this module?  If it is, I feel like there would need to be a bit of extra work done in case more than one special character ended up at the beginning or the end.

Thanks,

Randy

**Comment by elpete** [comment]
I don't think that is a normal API response to have a special character at the beginning.  If you want to clean up this API client specifically, you can make a custom Hyper client that has a `responseCallback` to clean up the data, if needed.

```
hyper.withResponseCallback( function( res ) {
    while( left( res.getData(), 1 ) != "{" ) {
        res.setData( removeChars( res.getData(), 1, 1 ) );
    }
} );
