### ISSUE TITLE
Issue when passing a binary value to the setBody() method

### ISSUE THREAD

**Issue by tsucaet** [coldbox-modules/hyper#48]
The HyperRequest automatically serialize complex values in the setBody() method.
Is there a way to tell Hyper to skip the serialization of the body because I need to pass a raw binary value with the setBody() method?

**Comment by elpete** [comment]
If you set your `bodyFormat` to something other than JSON, it will skip trying to serialize.

`hyper.setBodyFormat( "binary" ).setData( binaryObj ).send();`

**Comment by tsucaet** [comment]
Thanks, but I think it should be 'setBody' instead of 'setData'

`hyper.setBodyFormat( "binary" ).setBody( binaryObj ).send();`

**Comment by elpete** [comment]
Accurate. :-)
