### ISSUE TITLE
Retries don't seem to check for error and always re-execute the request

### ISSUE THREAD

**Issue by anderslars** [coldbox-modules/hyper#52]
Unless I am misunderstanding the retry approach, I see that retries always get executed, along with their delays, even when the previous result is a 200 response.

**Comment by elpete** [comment]
Hmmm…that’s not what our tests are showing. Do you have a reproducible example repo I can clone? Or a failing test case on this repo?

**Comment by anderslars** [comment]
Ah ok. Took a look at the tests and the docs. MB.  I assumed the retry () function would be called when a retry needed to happen. But its actually kind of like a shouldRetry call back- per the docs 'Returns the current callback function that is called to decide if a request should be retried.'

So if you don't provide a callback predicate to the retry() param - then that is the only case when hyper manages the Should Retry logic.
thanks for all your work on this. Pretty awesome.
